import assert from 'node:assert/strict';
import test from 'node:test';
import { createResilienceOwnerTools } from '../../extension/resilience-owner-tools.js';

function context(fingerprint='a',controls=[],overrides={}){return {binding:{tabId:7,frameId:0,sessionId:'owner-session',origin:'https://example.test',...overrides.binding},snapshot:{pageFingerprint:fingerprint,metadata:{origin:'https://example.test',title:overrides.title??'App'},mainText:overrides.mainText??'',accessibleControls:controls}};}
function harness(sequence){let now=0,index=0;const waits=[];const tools=createResilienceOwnerTools({getSnapshotContext:async()=>sequence[Math.min(index++,sequence.length-1)],waitRef:async(ms)=>{assert.ok(ms>=200);waits.push(ms);now+=ms;},nowRef:()=>now});return{tools,waits};}

test('catalog exposes only bounded read-only resilience waits',()=>{const h=harness([context()]);assert.deepEqual(h.tools.descriptors().map(d=>d.name),['toolbraid.resilience.wait_stable','toolbraid.resilience.wait_for_control']);assert.ok(h.tools.descriptors().every(d=>d.annotations.readOnlyHint&&d.annotations.idempotentHint));});

test('wait_stable resets its stability window when the exact fingerprint changes',async()=>{const h=harness([context('a'),context('b'),context('b'),context('b')]);const result=await h.tools.call('toolbraid.resilience.wait_stable',{timeoutMs:1200,stableForMs:400});assert.equal(result.stable,true);assert.equal(result.pageFingerprint,'b');assert.equal(result.stableForMs,400);assert.deepEqual(h.waits,[200,200,200]);});

test('wait_for_control requires exactly one enabled normalized name and optional role',async()=>{const h=harness([context('a',[]),context('b',[{ref:'disabled',name:' Continue ',role:'button',disabled:true},{ref:'live',name:'  Continue ',role:'button'}])]);const result=await h.tools.call('toolbraid.resilience.wait_for_control',{name:'continue',role:'BUTTON',timeoutMs:600});assert.deepEqual(result.control,{ref:'live',name:'  Continue ',role:'button'});const ambiguous=harness([context('a',[{ref:'a',name:'Send',role:'button'},{ref:'b',name:'Send',role:'button'}])]);await assert.rejects(ambiguous.tools.call('toolbraid.resilience.wait_for_control',{name:'send',timeoutMs:200}),e=>e.code==='RESILIENCE_WAIT_TIMEOUT');});

test('binding drift fails closed across tab, frame, session, and origin',async()=>{for(const changed of [{tabId:8},{frameId:2},{sessionId:'other-session'},{origin:'https://other.test'}]){const h=harness([context('a'),context('a',[],{binding:changed})]);await assert.rejects(h.tools.call('toolbraid.resilience.wait_stable',{timeoutMs:600,stableForMs:400}),e=>e.code==='RESILIENCE_BINDING_DRIFT');}});

test('human challenges and explicit rate limits return structured non-retrying blockers',async()=>{for(const [extra,kind,code] of [[{mainText:'Checking your browser - verify you are human'},'human-required','RESILIENCE_HUMAN_CHALLENGE'],[{mainText:'429 Too Many Requests - retry after 60 seconds'},'rate-limited','RESILIENCE_RATE_LIMITED']]){const h=harness([context('a',[],extra)]);const result=await h.tools.call('toolbraid.resilience.wait_stable',{timeoutMs:600,stableForMs:400});assert.deepEqual(result,{ok:false,blocked:true,blocker:{kind,code,humanRequired:true,retryAutomatically:false}});assert.deepEqual(h.waits,[]);}});

test('bounds, unknown calls, timeout, and invalidation are fail closed',async()=>{const h=harness([context('a')]);for(const args of [{timeoutMs:199},{timeoutMs:20001},{timeoutMs:400,stableForMs:600}])await assert.rejects(h.tools.call('toolbraid.resilience.wait_stable',args),e=>e.code==='RESILIENCE_BOUNDS_INVALID');await assert.rejects(h.tools.call('toolbraid.resilience.unknown',{}),e=>e.code==='RESILIENCE_TOOL_UNKNOWN');const timeout=harness([context('a')]);await assert.rejects(timeout.tools.call('toolbraid.resilience.wait_for_control',{name:'missing',timeoutMs:400}),e=>e.code==='RESILIENCE_WAIT_TIMEOUT');let release;let now=0;const tools=createResilienceOwnerTools({getSnapshotContext:async()=>context('a'),waitRef:()=>new Promise(r=>{release=()=>{now+=200;r();};}),nowRef:()=>now});const pending=tools.call('toolbraid.resilience.wait_stable',{timeoutMs:600,stableForMs:400});await Promise.resolve();tools.invalidate();release();await assert.rejects(pending,e=>e.code==='RESILIENCE_INVALIDATED');});
