import assert from 'node:assert/strict'; import test from 'node:test';
import { mkdtemp, readFile, symlink, writeFile } from 'node:fs/promises'; import os from 'node:os'; import path from 'node:path';
import { ScopedFilesystem } from '../../bridge/scoped-filesystem.mjs';
const OWNER='owner-1234567890abcdef'; async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'toolbraid-fs-'));return {root,fs:new ScopedFilesystem({selectFolder:async()=>root})};}
test('scoped filesystem uses opaque grants for atomic create read move and archive',async()=>{const {root,fs}=await fixture();const grant=await fs.grantRoot(OWNER);assert.equal(Object.hasOwn(grant,'path'),false);const w=await fs.write({rootId:grant.rootId,relativePath:'docs/a.txt',content:'hello'},OWNER);assert.equal(Object.hasOwn(w,'path'),false);const r=await fs.read({handle:w.handle},OWNER);assert.equal(Buffer.from(r.content,'base64').toString(),'hello');const m=await fs.move({handle:w.handle,destinationRelative:'docs/b.txt'},OWNER);assert.equal(await readFile(path.join(root,'docs/b.txt'),'utf8'),'hello');assert.equal((await fs.archive({handle:m.handle},OWNER)).archived,true);});
test('scoped moves preserve existing destinations and retain the source after rejection',async()=>{
  const {root,fs}=await fixture();const grant=await fs.grantRoot(OWNER);
  const source=await fs.write({rootId:grant.rootId,relativePath:'source.txt',content:'source'},OWNER);
  await fs.write({rootId:grant.rootId,relativePath:'existing.txt',content:'keep me'},OWNER);
  await assert.rejects(fs.move({handle:source.handle,destinationRelative:'existing.txt'},OWNER),{code:'FILES_EXISTS'});
  assert.equal(await readFile(path.join(root,'existing.txt'),'utf8'),'keep me');
  assert.equal(await readFile(path.join(root,'source.txt'),'utf8'),'source');
  await assert.rejects(fs.move({handle:source.handle,destinationRelative:'source.txt'},OWNER),{code:'FILES_EXISTS'});
  assert.equal(Buffer.from((await fs.read({handle:source.handle},OWNER)).content,'base64').toString(),'source');
});
test('scoped filesystem rejects traversal overwrite excess limits and cross-owner handles',async()=>{const {fs}=await fixture();const g=await fs.grantRoot(OWNER);const f=await fs.write({rootId:g.rootId,relativePath:'a.txt',content:'a'},OWNER);await assert.rejects(fs.write({rootId:g.rootId,relativePath:'../escape',content:'x'},OWNER),e=>e.code==='FILES_SCOPE_ESCAPE');await assert.rejects(fs.write({rootId:g.rootId,relativePath:'a.txt',content:'x'},OWNER),e=>e.code==='FILES_EXISTS');await assert.rejects(fs.read({handle:f.handle,maxBytes:1048577},OWNER),e=>e.code==='FILES_LIMIT_INVALID');await assert.rejects(fs.read({handle:f.handle},'other-owner-12345678'),e=>e.code==='FILES_HANDLE_NOT_FOUND');});
test('scoped filesystem rejects symlink or junction traversal',async(t)=>{const {root,fs}=await fixture();const out=await mkdtemp(path.join(os.tmpdir(),'toolbraid-out-'));await writeFile(path.join(out,'secret'),'x');try{await symlink(out,path.join(root,'link'),process.platform==='win32'?'junction':'dir');}catch{t.skip();return;}const g=await fs.grantRoot(OWNER);await assert.rejects(fs.list({rootId:g.rootId,relativePath:'link'},OWNER),e=>e.code==='FILES_REPARSE_REJECTED');});
test('scoped filesystem call boundary redacts raw filesystem paths',async()=>{const privatePath=path.join(os.tmpdir(),'owner-private-missing-folder');const fs=new ScopedFilesystem({selectFolder:async()=>privatePath});await assert.rejects(fs.call('files.root.create',{},OWNER),error=>error.code==='FILES_OPERATION_FAILED'&&!error.message.includes(privatePath)&&!error.message.includes('owner-private'));});
test('scoped filesystem reads one MiB files through transport-safe chunks',async()=>{const {fs}=await fixture(),g=await fs.grantRoot(OWNER),content='x'.repeat(300*1024),written=await fs.write({rootId:g.rootId,relativePath:'large.txt',content},OWNER);const first=await fs.read({handle:written.handle,offset:0,maxBytes:256*1024},OWNER),second=await fs.read({handle:written.handle,offset:first.size,maxBytes:256*1024},OWNER);assert.equal(first.size,256*1024);assert.equal(first.eof,false);assert.equal(second.size,44*1024);assert.equal(second.eof,true);assert.equal(Buffer.concat([Buffer.from(first.content,'base64'),Buffer.from(second.content,'base64')]).toString(),content);assert.equal(first.totalSize,300*1024);});
