import assert from 'node:assert/strict'; import test from 'node:test';
import { createPageSnapshot } from '../../src/universal/index.js'; import { createSiteAdapterRegistry } from '../../src/site-adapters/registry.js';
import { createYouTubeAdapter } from '../../src/site-adapters/youtube.js'; import { createInstagramAdapter } from '../../src/site-adapters/instagram.js'; import { createRedditAdapter } from '../../src/site-adapters/reddit.js';
function snap(origin,path,controls=[],mainText='Visible content'){return createPageSnapshot({metadata:{url:`${origin}${path}`,origin,title:'Content'},mainText,accessibleControls:controls,elementRefs:[{ref:'content-root',tagName:'article',role:'article',name:'Visible content'},...controls.map(c=>({ref:c.ref,parentRef:'content-root',tagName:c.role==='textbox'?'textarea':'button',...c}))]});}
for(const spec of [{name:'YouTube',origin:'https://www.youtube.com',path:'/watch?v=1',adapter:createYouTubeAdapter(),read:'read_youtube_content',action:'like_youtube_content',before:{ref:'like',role:'button',name:'Like'},after:{ref:'unlike',role:'button',name:'Unlike'}},{name:'Instagram',origin:'https://www.instagram.com',path:'/p/abc/',adapter:createInstagramAdapter(),read:'read_instagram_content',action:'like_instagram_content',before:{ref:'like',role:'button',name:'Like'},after:{ref:'unlike',role:'button',name:'Unlike'}},{name:'Reddit',origin:'https://www.reddit.com',path:'/r/test/comments/abc/post/',adapter:createRedditAdapter(),read:'read_reddit_content',action:'upvote_reddit_content',before:{ref:'up',role:'button',name:'Upvote'},after:{ref:'down',role:'button',name:'Remove upvote'}}]){
 test(`${spec.name} exposes conservative read and reaction tools with verified postconditions`,()=>{const r=createSiteAdapterRegistry({adapters:[spec.adapter]});const before=snap(spec.origin,spec.path,[spec.before]);const tools=r.generateTools(before);assert.deepEqual(tools.map(t=>t.name),[spec.read,spec.action]);assert.equal(tools[0].requiresApproval,false);assert.ok(tools[1].postcondition);const result=r.verifyPostcondition(tools[1],{tabId:1,frameId:0,sessionId:'content-social-session',beforeSnapshot:before,afterSnapshot:snap(spec.origin,spec.path,[spec.after])});assert.equal(result.status,'verified-success');});
 test(`${spec.name} suppresses all tools on authentication or challenge pages`,()=>{const r=createSiteAdapterRegistry({adapters:[spec.adapter]});assert.deepEqual(r.generateTools(snap(spec.origin,spec.path,[spec.before],'Security check: verify your identity with CAPTCHA')),[]);});
 test(`${spec.name} does not expose ambiguous mutation controls`,()=>{const r=createSiteAdapterRegistry({adapters:[spec.adapter]});const duplicate={...spec.before,ref:`${spec.before.ref}-2`};assert.deepEqual(r.generateTools(snap(spec.origin,spec.path,[spec.before,duplicate])).map(t=>t.name),[spec.read]);});
}

test('YouTube Studio exposes distinct title, description, and video publish tools only on exact studio routes',()=>{const r=createSiteAdapterRegistry({adapters:[createYouTubeAdapter()]});const tools=r.generateTools(snap('https://studio.youtube.com','/video/abc/edit',[{ref:'title',role:'textbox',name:'Title'},{ref:'description',role:'textbox',name:'Description'},{ref:'publish',role:'button',name:'Publish'}]));assert.deepEqual(tools.map(t=>t.name),['read_youtube_content','prepare_youtube_title','prepare_youtube_description','publish_youtube_video']);assert.ok(tools.slice(1).every(t=>t.postcondition));});
test('Instagram create flow exposes caption and post publishing without comment aliases',()=>{const r=createSiteAdapterRegistry({adapters:[createInstagramAdapter()]});const tools=r.generateTools(snap('https://www.instagram.com','/create/style/',[{ref:'caption',role:'textbox',name:'Write a caption'},{ref:'share',role:'button',name:'Share'}]));assert.deepEqual(tools.map(t=>t.name),['read_instagram_content','prepare_instagram_caption','publish_instagram_post']);});
test('Reddit submit flow exposes distinct post title, body, and publish tools',()=>{const r=createSiteAdapterRegistry({adapters:[createRedditAdapter()]});const tools=r.generateTools(snap('https://www.reddit.com','/r/test/submit/',[{ref:'title',role:'textbox',name:'Post title'},{ref:'body',role:'textbox',name:'Post body'},{ref:'post',role:'button',name:'Post'}]));assert.deepEqual(tools.map(t=>t.name),['read_reddit_content','prepare_reddit_post_title','prepare_reddit_post_body','publish_reddit_post']);assert.ok(tools.slice(1).every(t=>t.postcondition));});
test('creation workflows reject ambiguous editors and remain suppressed on challenges',()=>{const youtube=createSiteAdapterRegistry({adapters:[createYouTubeAdapter()]});assert.deepEqual(youtube.generateTools(snap('https://studio.youtube.com','/upload/',[{ref:'t1',role:'textbox',name:'Title'},{ref:'t2',role:'textbox',name:'Title'}])).map(t=>t.name),['read_youtube_content']);const reddit=createSiteAdapterRegistry({adapters:[createRedditAdapter()]});assert.deepEqual(reddit.generateTools(snap('https://www.reddit.com','/submit/',[{ref:'title',role:'textbox',name:'Title'}],'Security check CAPTCHA')),[]);});

test('public login CTA preserves read but suppresses account mutations',()=>{for(const [adapter,origin,path,control]of[[createYouTubeAdapter(),'https://www.youtube.com','/watch?v=1',{ref:'like',role:'button',name:'Like'}],[createInstagramAdapter(),'https://www.instagram.com','/p/a/',{ref:'like',role:'button',name:'Like'}],[createRedditAdapter(),'https://www.reddit.com','/r/a/comments/b/post/',{ref:'up',role:'button',name:'Upvote'}]]){const r=createSiteAdapterRegistry({adapters:[adapter]});assert.deepEqual(r.generateTools(snap(origin,path,[control],'Visible public content Sign in')).map(t=>t.classification),['read']);}});

test('response aliases fail closed when editor and publish labels disagree',()=>{for(const [adapter,origin,path]of[[createYouTubeAdapter(),'https://www.youtube.com','/watch?v=1'],[createInstagramAdapter(),'https://www.instagram.com','/p/a/'],[createRedditAdapter(),'https://www.reddit.com','/r/a/comments/b/post/']]){const r=createSiteAdapterRegistry({adapters:[adapter]});const names=r.generateTools(snap(origin,path,[{ref:'e',role:'textbox',name:'Reply'},{ref:'p',role:'button',name:'Comment'}])).map(t=>t.name);assert.equal(names.some(n=>/(?:draft|publish).*(?:reply|comment)/.test(n)),false);}});

test('mutations stay on known routes and ignore controls outside the unique semantic content root',()=>{const yt=createSiteAdapterRegistry({adapters:[createYouTubeAdapter()]});assert.deepEqual(yt.generateTools(snap('https://www.youtube.com','/feed/trending',[{ref:'like',role:'button',name:'Like'}])).map(t=>t.name),['read_youtube_content']);const raw=createPageSnapshot({metadata:{url:'https://www.instagram.com/p/a/',origin:'https://www.instagram.com'},accessibleControls:[{ref:'inside',role:'button',name:'Like'},{ref:'sidebar',role:'button',name:'Follow'}],elementRefs:[{ref:'root',tagName:'article'},{ref:'inside',tagName:'button',parentRef:'root'},{ref:'sidebar',tagName:'button'}]});const ig=createSiteAdapterRegistry({adapters:[createInstagramAdapter()]});assert.deepEqual(ig.generateTools(raw).map(t=>t.name),['read_instagram_content','like_instagram_content']);});

test('draft postconditions require exact requested text and publish does not succeed from target disappearance',()=>{const cases=[[createYouTubeAdapter(),'https://www.youtube.com','/watch?v=1','draft_youtube_comment','publish_youtube_comment','Comment'],[createInstagramAdapter(),'https://www.instagram.com','/p/a/','draft_instagram_comment','publish_instagram_comment','Post'],[createRedditAdapter(),'https://www.reddit.com','/r/a/comments/b/post/','draft_reddit_comment','publish_reddit_comment','Comment']];for(const[adapter,origin,path,draftName,publishName,buttonName]of cases){const r=createSiteAdapterRegistry({adapters:[adapter]}),before=snap(origin,path,[{ref:'e',role:'textbox',name:'Comment',value:''},{ref:'p',role:'button',name:buttonName}]),tools=r.generateTools(before),draft=tools.find(t=>t.name===draftName),publish=tools.find(t=>t.name===publishName),after=snap(origin,path,[{ref:'e',role:'textbox',name:'Comment',value:'exact text'}]);const ctx={tabId:1,frameId:0,sessionId:'social-postcondition',beforeSnapshot:before,afterSnapshot:after};assert.equal(r.verifyPostcondition(draft,{...ctx,preparedAction:{arguments:{text:'exact text'}}}).status,'verified-success');assert.equal(r.verifyPostcondition(draft,{...ctx,preparedAction:{arguments:{text:'wrong'}}}).status,'unverified');assert.equal(r.verifyPostcondition(publish,ctx).status,'unverified');}});

test('Instagram and Reddit postconditions reject query and hash drift',()=>{for(const[adapter,origin,path,action]of[[createInstagramAdapter(),'https://www.instagram.com','/p/a/?mode=one#x','like_instagram_content'],[createRedditAdapter(),'https://www.reddit.com','/r/a/comments/b/post/?sort=top#x','upvote_reddit_content']]){const r=createSiteAdapterRegistry({adapters:[adapter]}),before=snap(origin,path,[{ref:'x',role:'button',name:action.startsWith('like')?'Like':'Upvote'}]),tool=r.generateTools(before).find(t=>t.name===action),after=snap(origin,path.replace('one','two').replace('top','new').replace('#x','#y'),[{ref:'done',role:'button',name:action.startsWith('like')?'Unlike':'Remove upvote'}]);assert.equal(r.verifyPostcondition(tool,{tabId:1,frameId:0,sessionId:'query-drift-session',beforeSnapshot:before,afterSnapshot:after}).status,'unverified');}});
