import { execFile } from 'node:child_process';
import { copyFile, mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const OPS=new Set(['trim','concat','transcode','burn-subtitles','thumbnail']);
const MAX_INPUTS=32,MAX_DURATION=6*60*60,MAX_OUTPUT=20*1024*1024*1024,MAX_TIMEOUT=20*60*1000;
export class MediaJobError extends Error{constructor(code,message){super(message);this.name='MediaJobError';this.code=code;}}
const fail=(c,m)=>{throw new MediaJobError(c,m);},plain=v=>v&&typeof v==='object'&&!Array.isArray(v);
function number(v,name,min,max,required=false){if(v===undefined&&!required)return undefined;if(!Number.isFinite(v)||v<min||v>max)fail('MEDIA_JOB_BOUNDS',`${name} is outside its allowed bounds.`);return v;}
function expected(v){if(!plain(v))fail('MEDIA_JOB_OUTPUT_METADATA','Expected output metadata is required.');const duration=number(v.durationSeconds,'expected.durationSeconds',0,MAX_DURATION),bytes=number(v.maxBytes,'expected.maxBytes',1,MAX_OUTPUT,true);return{durationSeconds:duration,maxBytes:bytes,format:String(v.format??'').slice(0,32)};}
function quoteConcat(path){return `file '${String(path).replace(/'/g,"'\\''")}'`;}
function defaultAdapter({ffmpegPath='ffmpeg'}={}){return{run(args,{signal,timeoutMs}){return new Promise((resolve,reject)=>{execFile(ffmpegPath,args,{shell:false,windowsHide:true,timeout:timeoutMs,signal,maxBuffer:1024*1024},(error,stdout,stderr)=>error?reject(error):resolve({stdout,stderr}));});}};}
function filterPath(path){return String(path).replace(/\\/g,'/').replace(/([\\':,;\[\]])/g,'\\$1');}
function build(op,paths,spec,manifest){const out=paths.output;if(op==='trim'){const start=number(spec.startSeconds,'startSeconds',0,MAX_DURATION,true),duration=number(spec.durationSeconds,'durationSeconds',0.001,MAX_DURATION,true);return['-nostdin','-y','-ss',String(start),'-i',paths.inputs[0],'-t',String(duration),'-c','copy',out];}if(op==='concat')return['-nostdin','-y','-f','concat','-safe','0','-i',manifest,'-c','copy',out];if(op==='transcode'){const codec={h264:'libx264',h265:'libx265',vp9:'libvpx-vp9',av1:'libaom-av1'}[spec.codec??'h264'];if(!codec)fail('MEDIA_JOB_CODEC','Codec is not allowlisted.');return['-nostdin','-y','-i',paths.inputs[0],'-c:v',codec,'-c:a','aac',out];}if(op==='burn-subtitles')return['-nostdin','-y','-i',paths.inputs[0],'-vf',`subtitles=${filterPath(paths.inputs[1])}`,'-c:a','copy',out];const at=number(spec.atSeconds,'atSeconds',0,MAX_DURATION,true);return['-nostdin','-y','-ss',String(at),'-i',paths.inputs[0],'-frames:v','1',out];}
export function createMediaJobs({resolveGrant,ffmpegAdapter=defaultAdapter(),validateOutput,nowRef=Date.now,copySubtitle=copyFile}={}){if(typeof resolveGrant!=='function'||typeof validateOutput!=='function'||typeof ffmpegAdapter?.run!=='function'||typeof copySubtitle!=='function')throw new TypeError('resolveGrant, ffmpegAdapter.run, validateOutput, and copySubtitle are required.');const running=new Map();let sequence=0;
 async function run(spec={}){if(!plain(spec)||!OPS.has(spec.operation))fail('MEDIA_JOB_OPERATION','Operation is not allowlisted.');const inputs=Array.isArray(spec.inputGrants)?spec.inputGrants:[],required=spec.operation==='concat'?2:spec.operation==='burn-subtitles'?2:1;if(inputs.length<required||inputs.length>MAX_INPUTS||spec.operation!=='concat'&&inputs.length!==required)fail('MEDIA_JOB_INPUTS','Operation received an invalid bounded input count.');const timeoutMs=number(spec.timeoutMs??120000,'timeoutMs',100,MAX_TIMEOUT,true),want=expected(spec.expectedOutput),jobId=`media-${nowRef()}-${++sequence}`,controller=new AbortController();running.set(jobId,controller);let dir=null;
  try{const resolvedInputs=[];for(const grant of inputs){const r=await resolveGrant(grant,{mode:'read'});if(!plain(r)||typeof r.path!=='string'||!r.path)fail('MEDIA_JOB_GRANT','Input grant could not be resolved.');resolvedInputs.push(r.path);}const output=await resolveGrant(spec.outputGrant,{mode:'write'});if(!plain(output)||typeof output.path!=='string'||!output.path)fail('MEDIA_JOB_GRANT','Output grant could not be resolved.');let manifest=null;if(spec.operation==='concat'){dir=await mkdtemp(join(tmpdir(),'toolbraid-media-'));manifest=join(dir,'concat.txt');await writeFile(manifest,resolvedInputs.map(quoteConcat).join('\n'),'utf8');}if(spec.operation==='burn-subtitles'){dir=await mkdtemp(join(tmpdir(),'toolbraid-media-'));const safeSubtitle=join(dir,'subtitles.srt');await copySubtitle(resolvedInputs[1],safeSubtitle);resolvedInputs[1]=safeSubtitle;}const args=build(spec.operation,{inputs:resolvedInputs,output:output.path},spec,manifest);await ffmpegAdapter.run(Object.freeze(args),{signal:controller.signal,timeoutMs,jobId});const metadata=await validateOutput({grant:spec.outputGrant,path:output.path,expected:want,operation:spec.operation});if(!plain(metadata)||metadata.valid!==true||!Number.isFinite(metadata.bytes)||metadata.bytes<0||metadata.bytes>want.maxBytes)fail('MEDIA_JOB_OUTPUT_INVALID','Output metadata validation failed.');return Object.freeze({jobId,status:'complete',operation:spec.operation,output:Object.freeze({grant:spec.outputGrant,bytes:metadata.bytes,durationSeconds:metadata.durationSeconds??null,format:metadata.format??null})});}catch(e){if(controller.signal.aborted)fail('MEDIA_JOB_CANCELLED','Media job was cancelled.');if(e?.killed||e?.code==='ETIMEDOUT'||e?.name==='AbortError')fail('MEDIA_JOB_TIMEOUT','Media job timed out.');throw e;}finally{running.delete(jobId);if(dir)await rm(dir,{recursive:true,force:true});}}
 function cancel(jobId){const c=running.get(jobId);if(!c)return false;c.abort();return true;}return Object.freeze({run,cancel,operations:Object.freeze([...OPS]),runningCount:()=>running.size});}
