import { createDurableMissionRunner } from '../local-agent/durable-runner.mjs';
import { createLocalScheduler } from '../local-agent/scheduler.mjs';

const SECRET_KEY = /^(?:password|passcode|secret|token|api[_-]?key|authorization|cookie|otp|cvv|resolvedLocalPath|expectedFile)$/iu;
const MAX_PUBLIC_TEXT = 4096;
function plain(value){if(!value||typeof value!=='object'||Array.isArray(value))return false;const p=Object.getPrototypeOf(value);return p===Object.prototype||p===null;}
function safeId(value,field){if(typeof value!=='string'||!/^[A-Za-z0-9_.:-]{1,128}$/.test(value))throw new TypeError(`${field} is invalid.`);return value;}
function safeValue(value,depth=0,nodes={count:0}){if(depth>6||++nodes.count>512)throw new RangeError('Control payload is too complex.');if(value===null||typeof value==='boolean'||Number.isFinite(value))return value;if(typeof value==='string'){if(value.length>MAX_PUBLIC_TEXT)throw new RangeError('Control text exceeds 4096 characters; the exact payload was not stored or dispatched.');return value;}if(Array.isArray(value)){if(value.length>128)throw new RangeError('Control payload array is too large.');return value.map(v=>safeValue(v,depth+1,nodes));}if(plain(value)){const entries=Object.entries(value);if(entries.length>128)throw new RangeError('Control payload object is too large.');const out={};for(const [key,item]of entries){if(SECRET_KEY.test(key))throw new TypeError('Secrets are not accepted by durable control.');if(['__proto__','constructor','prototype'].includes(key))throw new TypeError('Reserved keys are not accepted by durable control.');out[key]=safeValue(item,depth+1,nodes);}return out;}throw new TypeError('Control payload contains an unsupported value.');}
function exactCall(value){if(!plain(value)||Object.keys(value).sort().join(',')!=='arguments,toolName'||!plain(value.arguments))throw new TypeError('Tool input must be exactly {toolName, arguments}, with object arguments.');return Object.freeze({toolName:safeId(value.toolName,'toolName'),arguments:safeValue(value.arguments)});}
function publicMission(state){if(!state)return null;return Object.freeze({version:state.version,missionId:state.missionId,status:state.status,cancelled:state.cancelled===true,createdAt:state.createdAt,updatedAt:state.updatedAt,steps:Object.freeze((state.steps??[]).slice(0,64).map(s=>Object.freeze({id:s.id,kind:s.kind,status:s.status,attempts:s.attempts,error:s.error?Object.freeze({code:String(s.error.code??'FAILED').slice(0,64),message:String(s.error.message??'Failed').slice(0,512)}):null})))});}
function publicSchedule(s){const argumentsValue=safeValue(s.payload.arguments),argumentBytes=new TextEncoder().encode(JSON.stringify(argumentsValue)).byteLength;return Object.freeze({id:s.id,type:s.type,at:s.at,intervalMs:s.intervalMs,missedRunPolicy:s.missedRunPolicy,lane:s.lane,paused:s.paused,lastRunAt:s.lastRunAt,nextRunAt:s.nextRunAt,lastOutcome:s.lastOutcome??null,lastError:s.lastError?Object.freeze({code:String(s.lastError.code??'FAILED').slice(0,64),message:String(s.lastError.message??'Failed').slice(0,512)}):null,payload:Object.freeze({toolName:s.payload.toolName,argumentBytes})});}

export function createDurableControl({store,dispatch,now=()=>Date.now(),setTimer=setTimeout,clearTimer=clearTimeout,missionKey='toolbraid.durable-control.mission.v1',scheduleKey='toolbraid.durable-control.scheduler.v1'}={}){
  if(!store||typeof store.read!=='function'||typeof store.write!=='function')throw new TypeError('An atomic store is required.');if(typeof dispatch!=='function')throw new TypeError('dispatch is required.');
  const invoke=async({toolName,arguments:args},context)=>safeValue(await dispatch(Object.freeze({toolName,arguments:safeValue(args),...context})));
  const runner=createDurableMissionRunner({store,key:missionKey,now,dispatch:({missionId,stepId,kind,input,idempotencyKey})=>invoke(exactCall(input),{missionId,stepId,kind,idempotencyKey})});
  const scheduler=createLocalScheduler({store,key:scheduleKey,now,setTimer,clearTimer,dispatch:({scheduleId,payload,scheduledFor,lane})=>invoke(exactCall(payload),{scheduleId,scheduledFor,lane})});
  const mission=Object.freeze({
    async create(input={}){if(!plain(input)||!Array.isArray(input.plan))throw new TypeError('mission.create requires a plan.');const plan=input.plan.map((step)=>{if(!plain(step))throw new TypeError('Mission step is invalid.');const allowed=new Set(['id','kind','dependsOn','input','idempotencyKey']);if(Object.keys(step).some(k=>!allowed.has(k)))throw new TypeError('Mission step contains an unknown field.');return {...step,id:safeId(step.id,'step.id'),kind:step.kind,input:exactCall(step.input)};});return publicMission(await runner.create({missionId:safeId(input.missionId,'missionId'),plan}));},
    async run(){return publicMission(await runner.run());},async state(){return publicMission(await runner.state());},async cancel(){return publicMission(await runner.cancel());},async clear(){const state=await runner.state();if(state&&!['complete','failed','blocked','outcome-unknown','cancelled'].includes(state.status))throw new Error('Only a terminal mission can be cleared.');await store.write(missionKey,undefined);return Object.freeze({cleared:Boolean(state)});},
  });
  const schedule=Object.freeze({
    async add(input={}){if(!plain(input))throw new TypeError('schedule.add input is invalid.');const allowed=new Set(['id','type','at','intervalMs','missedRunPolicy','lane','payload']);if(Object.keys(input).some(k=>!allowed.has(k)))throw new TypeError('Schedule contains an unknown field.');if(!['read','mutation'].includes(input.lane))throw new TypeError('Schedule lane must be read or mutation.');return publicSchedule(await scheduler.add({...input,id:safeId(input.id,'schedule.id'),payload:exactCall(input.payload)}));},
    async list(){const state=await scheduler.state();return Object.freeze((state.schedules??[]).map(publicSchedule));},
    async pause(id){const result=await scheduler.pause(safeId(id,'schedule.id'));return result?publicSchedule(result):null;},async resume(id){const result=await scheduler.resume(safeId(id,'schedule.id'));return result?publicSchedule(result):null;},async delete(id){return scheduler.delete(safeId(id,'schedule.id'));},async tick(){const state=await scheduler.tick();return Object.freeze((state.schedules??[]).map(publicSchedule));},async start(){await scheduler.start();return this.list();},
  });
  return Object.freeze({mission,schedule});
}
