import { readDescriptor } from './common.js';
import { normalizedControlText, uniqueControl, verifiedActionDescriptor } from './action.js';
import { elementFingerprint } from '../universal/snapshot.js';
import { validateToolDescriptor } from '../universal/tools.js';

const BLOCKED=/(?:log\s*in|sign\s*in|captcha|verification\s*code|two[- ]factor|security\s*check|challenge|verify\s+your\s+account)/i;
const IDS=Object.freeze({prepare:'discord.message.prepare.v1',send:'discord.message.send.v1'});
function text(v){return String(v??'').replace(/\s+/g,' ').trim();}
function exact(snapshot){try{const u=new URL(snapshot.metadata.url);return u.protocol==='https:'&&u.hostname.toLowerCase()==='discord.com'&&!u.port&&!u.username&&!u.password&&/^\/channels\/(?:@me|\d+)\/\d+(?:\/|$)/.test(u.pathname);}catch{return false;}}
function blocked(s){return BLOCKED.test(`${s.metadata.title??''} ${s.mainText??''} ${s.accessibleControls.map(c=>`${c.name??''} ${c.type??''}`).join(' ')}`);}
function editor(c){const n=normalizedControlText(c).toLowerCase();return(text(c?.role).toLowerCase()==='textbox'||['text','textarea','contenteditable'].includes(text(c?.type).toLowerCase()))&&/(?:message|mesaj)/i.test(n)&&!/(?:search|caut)/i.test(n);}
function send(c){return text(c?.role).toLowerCase()==='button'&&/^(?:send|trimite)(?:\s+message)?$/i.test(normalizedControlText(c));}
function active(s){return Boolean(uniqueControl(s,editor))&&!blocked(s);}
function route(s){try{const u=new URL(s.metadata.url);return exact(s)?`${u.origin}${u.pathname}`:null;}catch{return null;}}
function contract(id,v){return Object.freeze({version:1,id,adapterId:'discord-web',adapterVersion:String(v),observation:'page-snapshot'});}
function action(s,o,id,v){const base=verifiedActionDescriptor(s,o),d={...base,postcondition:contract(id,v)};validateToolDescriptor(d);return Object.freeze(d);}
function result(status,reason,a,evidence={}){return{status,reasonCode:reason,evidence,...(a?.pageFingerprint?{afterPageFingerprint:a.pageFingerprint}:{})};}
function bound(t,s,p){const m=s.accessibleControls.filter(c=>c.ref===t?.target?.ref&&p(c)&&elementFingerprint(c)===t?.target?.targetFingerprint);return m.length===1?m[0]:null;}
function verify({tool,contract:c,beforeSnapshot:b,afterSnapshot:a,preparedAction:p}={},v){if(!b||!a||route(b)!==route(a))return result('unverified','DISCORD_ROUTE_DRIFT',a);const id=tool?.name==='prepare_discord_message'?IDS.prepare:tool?.name==='send_prepared_discord_message'?IDS.send:null;c=c??tool?.postcondition;if(!id||c?.id!==id||c?.adapterId!=='discord-web'||String(c?.adapterVersion)!==String(v))return result('unverified','DISCORD_CONTRACT_MISMATCH',a);const target=bound(tool,b,tool.name.startsWith('prepare_')?editor:send);if(!target)return result('unverified','DISCORD_TARGET_BINDING_DRIFT',a);if(tool.name.startsWith('prepare_')){const wanted=text(p?.arguments?.text??p?.normalizedArguments?.text),ed=uniqueControl(a,editor);return wanted&&ed&&ed.ref===target.ref&&text(ed.value)===wanted?result('verified-success','DISCORD_DRAFT_CONFIRMED',a,{editorRef:ed.ref}):result('unverified','DISCORD_DRAFT_NOT_CONFIRMED',a);}const be=uniqueControl(b,editor),ae=uniqueControl(a,editor),buttons=a.accessibleControls.filter(send),cleared=Boolean(be&&text(be.value)&&ae&&ae.ref===be.ref&&text(ae.value)===''),changed=buttons.length===0||(buttons.length===1&&!buttons.some(x=>x.ref===target.ref&&elementFingerprint(x)===elementFingerprint(target)));return cleared||changed?result('verified-success','DISCORD_SEND_CONFIRMED',a,{composerCleared:cleared,sendControlChanged:changed}):result('unverified','DISCORD_SEND_NOT_CONFIRMED',a,{composerCleared:false,sendControlChanged:false});}
function read(s){return Object.freeze({service:'discord',title:text(s.metadata.title).slice(0,512),heading:text(s.headings?.[0]?.text).slice(0,512)||null,visibleText:text(s.mainText).slice(0,20000),url:s.metadata.url,pageFingerprint:s.pageFingerprint,untrustedContent:true});}
export function createDiscordWebAdapter({version='1'}={}){return Object.freeze({id:'discord-web',version,priority:130,matches(s){return exact(s)&&active(s);},generateTools(s){if(!exact(s)||!active(s))return Object.freeze([]);const tools=[readDescriptor(s,{adapterId:'discord-web',adapterVersion:version,sourceType:'verified-adapter',name:'read_discord_channel',title:'Read Discord channel',description:'Read the currently visible active Discord channel or direct-message context.',effectSummary:'Read only the active visible Discord context.',evidence:[{code:'DISCORD_ACTIVE_CHANNEL',adapterVersion:version}]})];const composer=uniqueControl(s,editor),button=uniqueControl(s,send);if(composer)tools.push(action(s,{adapterId:'discord-web',adapterVersion:version,name:'prepare_discord_message',title:'Prepare Discord message',description:'Stage text in the exact active visible Discord composer without sending it.',risk:'account-content',target:composer,inputSchema:{type:'object',properties:{text:{type:'string',minLength:1,maxLength:2000}},required:['text'],additionalProperties:false},summary:'Prepare a message in the active Discord context.'},IDS.prepare,version));if(button)tools.push(action(s,{adapterId:'discord-web',adapterVersion:version,name:'send_prepared_discord_message',title:'Send prepared Discord message',description:'Send the message already prepared in the exact active visible Discord context.',risk:'account-content',target:button,summary:'Send the prepared message to the active Discord context.'},IDS.send,version));return Object.freeze(tools);},executeRead(tool,s){if(!exact(s)||!active(s))throw new Error('Discord active context changed.');if(tool.name==='read_discord_channel')return read(s);throw new Error('Unsupported Discord read tool.');},verifyPostcondition(c){return verify(c,version);}});}
